name: CI/CD for Stock Data Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *' # Run every 6 hours (0:00, 6:00, 12:00, 18:00)

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run ETL pipeline and Forecast pipeline
      - name: Run Pipelines
        env:
          API_KEY: ${{ secrets.API_KEY }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          python etl_pipeline.py && python forecast_pipeline.py
